@host=http://localhost:5013

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YTQ5ZTJiOC1mMGJkLTQ2MjItODVkZS1hNjE1YjRmYjVlYmIiLCJnaXZlbl9uYW1lIjoiQW5kcmV5IiwiZmFtaWx5X25hbWUiOiJLaG9kYWsiLCJqdGkiOiJjYTQ2MWYyZC0xMmM1LTQ3ZDctYmVkNi00MTU3NTQwZGM3MmIiLCJleHAiOjE2OTkyOTYxMzIsImlzcyI6IkRpbm5lclByb2plY3QiLCJhdWQiOiJEaW5uZXJQcm9qZWN0In0.vhwOCM0L6NJ5iyal-R06i8b_aLqvz3hbsknxkdV6x8I